BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Character" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"EpisodeID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID")
);
CREATE TABLE IF NOT EXISTS "Episode" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	INTEGER,
	"Description"	INTEGER,
	"Orderr"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "User" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Email"	TEXT,
	"Password"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
